### ISSUE TITLE
Add <noscript> to piwik_code()

### ISSUE THREAD

**Issue by nwoetzel** [webfactory/piwik-bundle#11]
Piwik FAQ: [How do I enable tracking for visitors that have disabled Javascript?](http://piwik.org/faq/how-to/faq_176/)

When the visitor disables javascript, there would be no tracking. Piwik suggest to add
```
<noscript><p><img src="http://piwik-server.com/piwik.php?idsite=1&rec=1" style="border:0" alt="" /></p></noscript>
```
which does not have the full tracking functionality, but is a good backup plan.
Could I submit a pull request to include this?
Would you prefer to have an argument to the piwik_code function call
```
{{ piwik_code(noscript=true) }}
```
Or should it be a configuration parameter? Or anything else?

**Comment by mpdude** [comment]
I think it would be great to have this included so our users don't need to remember this :)

Looking at the FAQ page you linked, there seem to be some parameters (`rec` and `bots` in particular) that would be nice to have as configuration values with sensible defaults.

Do you understand the importance of having `rec` set?

**Comment by nwoetzel** [comment]
Thanks for the quick reply.
http://developer.piwik.org/2.x/api-reference/tracking-api
So it seems that without `rec=1` there would be no tracking. I guess that it is there, so that if you no want to disable tracking (like in development mode) it would still generate the url, the browser loads it - but the piwik-server would ignore it. So you can easily disable tracking without removing the code...
In theory, I would go as far as to allow setting all HTTP API query parameters is wanted. And in the configuration, as you said, define sensible defaults (e.g. site_id, rec, api_v).
One could even take care of the `rand=1285698456-0123456` that is suggested to include to prevent caching of requests. (I think the javascript tracking code does that by default)
Now that I think about it, having a second function
```{{ piwik_code_api() }}```
that just generates the
```<img src="http://piwik-server.com/piwik.php?idsite=1&rec=1" style="border:0" alt="" />``` portion would be cleanest. And using
```{{ piwik_code(noscript=true) }}```
would be very close to
```
{{ piwik_code() }}
<noscrip><p>{{ piwik_code_api() }}</p></noscript>
```
where `noscript=true` would pretty much just be a helper for the above. And this could be set in the configuration as default, so that no layout has to be changed.

**Comment by TomaszGasior** [comment]
It seems to be this bug can be closed sine last commits which solve this issue.

**Comment by mpdude** [comment]
Thanks!
