### ISSUE TITLE
Support Twig 2.0

### ISSUE THREAD

**Issue by alexsegura** [webfactory/piwik-bundle#13]
Hello. 

The bundle requires `twig: ~1.0`, which make it impossible to use with Twig 2.0.

**Comment by mpdude** [comment]
@alexsegura Thanks for your report!

Are there any updates we need to make, in particular to the Twig Extension class, to make it work?

Have you successfully tried this bundle with Twig 2?

**Comment by alexsegura** [comment]
Nope, I haven't tested it. 
Unfortunately I had to remove this bundle in a hurry on a project where I'm using Sylius.

**Comment by MalteWunsch** [comment]
Fixed with PR #15, released as 2.5.0.
