### ISSUE TITLE
Support for Symfony 4 / Flex

### ISSUE THREAD

**Issue by BernhardWebstudio** [webfactory/piwik-bundle#14]
As this project requires symfony/symfony, which is added as conflicting package for flex, they do not work together. The relevant dependencies of symfony can be added separately to reach support. 

Is someone already working on this, or do you mind a pull request?

**Comment by BernhardWebstudio** [comment]
Thank you for the fast response. My suggestion is in [#15](https://github.com/webfactory/piwik-bundle/pull/15) and would fix issue [#13](https://github.com/webfactory/piwik-bundle/issues/13) too.

**Comment by MalteWunsch** [comment]
Merged your PR #15
