### ISSUE TITLE
README: Configuration fix

### ISSUE THREAD

**Issue by bretrzaun** [webfactory/piwik-bundle#16]
The example documentation in the README should say:
`disabled: '%kernel.debug%'`
instead of:
`disabled: %kernel.debug%`

Otherwise Symfony(4) will complain about invalid YAML.

**Comment by mpdude** [comment]
Maybe something got lost in formatting here?

**Comment by bretrzaun** [comment]
Yes - the (important) quotes got lost...

**Comment by mpdude** [comment]
Thank you @bretrzaun
