### ISSUE TITLE
Visits are counted twice

### ISSUE THREAD

**Issue by TomaszGasior** [webfactory/piwik-bundle#19]
In Chrome and WebKit-based browsers Matomo calculates visits twice. It's because of this line: https://github.com/webfactory/piwik-bundle/blob/2.5.1/Twig/Extension.php#L50 Please remove it.

**Comment by mpdude** [comment]
Please give dev-master a try.

**Comment by TomaszGasior** [comment]
I tested this change on production ;) so I'm sure it works.

**Comment by mpdude** [comment]
Fix released as 2.5.2.
