### ISSUE TITLE
Deprecation in Symfony 4.3

### ISSUE THREAD

**Issue by TomaszGasior** [webfactory/piwik-bundle#21]
After update to sf 4.3 I have this deprecation message in tests and profiler:

> The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "webfactory_piwik" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

**Comment by mpdude** [comment]
What’s the best way of gracefully handling this for both Symfony <4.3 and/or above?

**Comment by TomaszGasior** [comment]
You may want to go to https://symfony-devs.slack.com to ask question.
