### ISSUE TITLE
Symfony deprecation

### ISSUE THREAD

**Issue by bretrzaun** [webfactory/piwik-bundle#38]
Using Symfony 5.4 we see the following deprecation message when running our tests:
` 1x: Method "Twig\Extension\ExtensionInterface::getFunctions()" might add "array" as a native return type declaration in the future. Do the same in implementation "Webfactory\Bundle\PiwikBundle\Twig\Extension" now to avoid errors or add an explicit @return annotation to suppress this message.`

Should be any easy fix. Do you want a PR for that?

**Comment by mpdude** [comment]
Sorry @bretrzaun, I somehow missed this issue. #39 will address it.
